// Word lists for the on-site filter. Slurs and explicit sexual terms are ROT13
// so the plaintext is not sitting in the repo and is never rendered on a page.
// Decode only inside the classifier.

export function rot13(value) {
  return String(value).replace(/[a-z]/gi, (char) => {
    const base = char <= "Z" ? 65 : 97;
    return String.fromCharCode(((char.charCodeAt(0) - base + 13) % 26) + base);
  });
}

export const SLUR_ROT13 = [
  "avttre",
  "avttref",
  "avttn",
  "avttnf",
  "xvxr",
  "xvxrf",
  "fcvp",
  "fcvpf",
  "puvax",
  "puvaxf",
  "tbbx",
  "tbbxf",
  "jrgonpx",
  "jrgonpxf",
  "gbjryurnq",
  "gbjryurnqf",
  "enturnq",
  "enturnqf",
  "ornare",
  "ornaref",
  "snttbg",
  "snttbgf",
  "snt",
  "qlxr",
  "qlxrf",
  "genaal",
  "genaavrf",
  "ergneq",
  "ergneqf",
  "ergneqrq",
];

export const SEXUAL_ROT13 = [
  "cbea",
  "cbeab",
  "cbeabtencul",
  "ahqr",
  "ahqrf",
  "anxrq",
  "oybjwbo",
  "unaqwbo",
  "nany",
  "betnfz",
  "ubeal",
  "qvpx",
  "pbpx",
  "chffl",
  "obbof",
  "gvgf",
  "juber",
  "fyhg",
];

export const VIOLENCE_WORDS = [
  "kill",
  "killing",
  "murder",
  "murdered",
  "murdering",
  "shoot",
  "shooting",
  "bomb",
  "bombing",
  "stab",
  "stabbing",
  "execute",
  "executing",
];

export const RAPE_WORDS = ["rape", "raping", "raped"];

export const TARGET_WORDS = [
  "human",
  "humans",
  "person",
  "people",
  "someone",
  "somebody",
  "everyone",
  "anybody",
  "kid",
  "kids",
  "child",
  "children",
  "baby",
  "babies",
  "civilian",
  "civilians",
  "crowd",
  "him",
  "her",
  "you",
  "them",
  "me",
  "us",
  "man",
  "woman",
  "men",
  "women",
  "school",
  "church",
  "mosque",
  "synagogue",
  "temple",
  "hospital",
  "office",
  "building",
  "stadium",
  "mall",
  "airport",
  "city",
];

export const GROUP_PHRASES = [
  "black people",
  "white people",
  "asian people",
  "asians",
  "jews",
  "jewish people",
  "muslims",
  "muslim people",
  "christians",
  "hindus",
  "sikhs",
  "arabs",
  "arab people",
  "hispanics",
  "hispanic people",
  "latinos",
  "latinas",
  "latino people",
  "indigenous people",
  "immigrants",
  "refugees",
  "gay people",
  "gays",
  "lesbians",
  "lesbian people",
  "trans people",
  "transgender people",
  "bisexual people",
  "disabled people",
  "women",
  "men",
];

export const SPAM_WORDS = ["buy", "discount", "discounts"];

export const SPAM_PHRASES = ["crypto giveaway"];
